# Generated by Django 4.1.7 on 2023-04-02 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locadora_carros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_carro_alugado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora_carros.carro'),
        ),
    ]
